version: "3.9"

services:
  dbmongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend
    env_file: .env
    volumes:
      - dbbankdata:/data/db

  bankapi:
    build:
      context: bankapi
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    depends_on:
      - dbmongo
    volumes:
      - ./bankapi:/app
      - bankres:/app/resources
    networks:
      - backend
    env_file: .env

  invoiceapi:
    build:
      context: invoiceapi
      dockerfile: Dockerfile
    ports:
      - "8101:5000"
    volumes:
      - ./invoiceapi:/app
      - invoicedata:/app/resources/pdf
    networks:
      - backend

  express:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - bankapi
    ports:
      - 6001:6001
    volumes:
      - ./backend:/app
      - invoicedata:/app/invoicedata
      - bankres:/app/bankres
    networks:
      - frontend
      - backend
    env_file: .env

networks:
  frontend:
  backend:

volumes:
  dbbankdata:
  invoicedata:
  bankres:
