FROM python:3.8-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y wkhtmltopdf
COPY invGenSrc/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY invGenSrc/ .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
